/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Enum: typeof import('ts-brix')['Enum']
  const P: typeof import('ts-brix')['P']
  const Temporal: typeof import('temporal-polyfill')['Temporal']
  const afterNavigate: typeof import('$app/navigation')['afterNavigate']
  const beforeNavigate: typeof import('$app/navigation')['beforeNavigate']
  const defer: typeof import('ts-brix')['defer']
  const err: typeof import('ts-brix')['err']
  const except: typeof import('ts-brix')['except']
  const goto: typeof import('$app/navigation')['goto']
  const match: typeof import('ts-brix')['match']
  const none: typeof import('ts-brix')['none']
  const ofType: typeof import('ts-brix')['ofType']
  const ofTypes: typeof import('ts-brix')['ofTypes']
  const ok: typeof import('ts-brix')['ok']
  const onDestroy: typeof import('svelte')['onDestroy']
  const onMount: typeof import('svelte')['onMount']
  const onNavigate: typeof import('$app/navigation')['onNavigate']
  const pattern: typeof import('ts-brix')['pattern']
  const pipe: typeof import('ts-brix')['pipe']
  const preloadCode: typeof import('$app/navigation')['preloadCode']
  const preloadData: typeof import('$app/navigation')['preloadData']
  const pushState: typeof import('$app/navigation')['pushState']
  const replaceState: typeof import('$app/navigation')['replaceState']
  const route: typeof import('$lib/ROUTES')['route']
  const satisfiesAs: typeof import('./src/lib/globals/types')['satisfiesAs']
  const some: typeof import('ts-brix')['some']
  const types: typeof import('ts-brix')['types']
  const unwrapType: typeof import('./src/lib/globals/types')['unwrapType']
}
