packages:
  - packages/*
  - app
  - screening

catalog:
  "@tauri-apps/api": ^2.0.1
  "@tauri-apps/cli": ^2.0.1

catalogs:
  qa:
    "@eslint/js": ^9.12.0
    "@faker-js/faker": ^9.0.3
    "@testing-library/svelte": ^5.2.3
    "@testing-library/user-event": ^14.5.2
    "@total-typescript/ts-reset": ^0.6.1
    "@types/dom-view-transitions": ^1.0.5
    "@types/node": ^22.7.4
    "@vitest/coverage-v8": ^2.1.2
    eslint: ^9.12.0
    eslint-config-prettier: ^9.1.0
    eslint-define-config: ^2.1.0
    eslint-plugin-jsdoc: ^50.3.1
    eslint-plugin-oxlint: ^0.9.9
    eslint-plugin-promise: ^7.1.0
    eslint-plugin-simple-import-sort: ^12.1.1
    eslint-plugin-sonarjs: ^2.0.3
    eslint-plugin-svelte: ^2.44.1
    eslint-plugin-unicorn: ^56.0.0
    eslint-plugin-vitest: ^0.5.4
    globals: ^15.10.0
    jsdom: ^25.0.1
    msw: ^2.4.9
    oxlint: ^0.9.9
    prettier: ^3.3.3
    typescript: ^5.6.2
    typescript-eslint: ^8.8.0
    vitest: ^2.1.2

  css:
    "@tailwindcss/container-queries": ^0.1.1
    "@tailwindcss/typography": ^0.5.15
    fluid-tailwind: ^1.0.3
    tailwind-scrollbar: ^3.1.0
    tailwindcss: ^3.4.13
    tailwindcss-hover: ^0.0.0
