packages:
  - packages/*
  - apps/*
  - screening
catalog:
  '@tauri-apps/api': ^2.1.1
  '@tauri-apps/cli': ^2.1.0
  '@types/dom-view-transitions': ^1.0.5
  '@types/node': ^22.10.1
catalogs:
  qa:
    '@eslint/js': ^9.16.0
    '@faker-js/faker': ^9.3.0
    '@fast-check/vitest': ^0.1.4
    '@stylistic/eslint-plugin-js': ^2.12.0
    '@stylistic/eslint-plugin-ts': ^2.12.0
    '@tanstack/eslint-plugin-query': ^5.62.1
    '@testing-library/jest-dom': ^6.6.3
    '@testing-library/svelte': ^5.2.6
    '@testing-library/user-event': ^14.5.2
    '@total-typescript/ts-reset': ^0.6.1
    '@vitest/coverage-v8': ^2.1.8
    '@vitest/eslint-plugin': ^1.1.14
    eslint: ^9.16.0
    eslint-config-prettier: ^9.1.0
    eslint-define-config: ^2.1.0
    eslint-plugin-jest-dom: ^5.5.0
    eslint-plugin-jsdoc: ^50.6.0
    eslint-plugin-oxlint: ^0.14.1
    eslint-plugin-perfectionist: ^4.2.0
    eslint-plugin-playwright: ^2.1.0
    eslint-plugin-promise: ^7.2.1
    eslint-plugin-simple-import-sort: ^12.1.1
    eslint-plugin-sonarjs: ^3.0.1
    eslint-plugin-svelte: ^2.46.1
    eslint-plugin-testing-library: ^7.1.1
    eslint-plugin-unicorn: ^56.0.1
    eslint-plugin-vitest: ^0.5.4
    globals: ^15.13.0
    jsdom: ^25.0.1
    msw: ^2.6.8
    oxlint: ^0.14.1
    prettier: ^3.4.2
    typescript: ^5.7.2
    typescript-eslint: ^8.17.0
    vitest: ^2.1.8
  css:
    '@tailwindcss/container-queries': ^0.1.1
    '@tailwindcss/typography': ^0.5.15
    fluid-tailwind: ^1.0.4
    tailwind-scrollbar: ^3.1.0
    tailwindcss: ^3.4.16
    tailwindcss-hover: ^0.0.0
