packages:
  - packages/*
  - apps/*
  - screening

catalog:
  "@tauri-apps/api": ^2.1.1
  "@tauri-apps/cli": ^2.1.0
  "@types/dom-view-transitions": ^1.0.5
  "@types/node": ^22.9.0

catalogs:
  qa:
    "@eslint/js": ^9.15.0
    "@fast-check/vitest": ^0.1.4
    "@faker-js/faker": ^9.2.0
    "@stylistic/eslint-plugin-js": ^2.10.1
    "@stylistic/eslint-plugin-ts": ^2.10.1
    "@tanstack/eslint-plugin-query": ^5.60.1
    "@testing-library/jest-dom": ^6.6.3
    "@testing-library/svelte": ^5.2.4
    "@testing-library/user-event": ^14.5.2
    "@total-typescript/ts-reset": ^0.6.1
    "@vitest/coverage-v8": ^2.1.5
    "@vitest/eslint-plugin": ^1.1.10
    eslint: ^9.15.0
    eslint-config-prettier: ^9.1.0
    eslint-define-config: ^2.1.0
    eslint-plugin-jest-dom: ^5.4.0
    eslint-plugin-jsdoc: ^50.5.0
    eslint-plugin-oxlint: ^0.11.1
    eslint-plugin-perfectionist: ^3.9.1
    eslint-plugin-playwright: ^2.0.1
    eslint-plugin-promise: ^7.1.0
    eslint-plugin-simple-import-sort: ^12.1.1
    eslint-plugin-sonarjs: ^2.0.4
    eslint-plugin-svelte: ^2.46.0
    eslint-plugin-testing-library: ^6.4.0
    eslint-plugin-unicorn: ^56.0.0
    eslint-plugin-vitest: ^0.5.4
    globals: ^15.12.0
    jsdom: ^25.0.1
    msw: ^2.6.5
    oxlint: ^0.11.1
    prettier: ^3.3.3
    typescript: ^5.6.3
    typescript-eslint: ^8.14.0
    vitest: ^2.1.5

  css:
    "@tailwindcss/container-queries": ^0.1.1
    "@tailwindcss/typography": ^0.5.15
    fluid-tailwind: ^1.0.4
    tailwind-scrollbar: ^3.1.0
    tailwindcss: ^3.4.15
    tailwindcss-hover: ^0.0.0
