// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const Big: typeof import("./src/lib/features/typography/components/big/Big.svelte")["default"]
    const BlockQuote: typeof import("./src/lib/features/typography/components/blockquote/BlockQuote.svelte")["default"]
    const Heading: typeof import("./src/lib/features/typography/components/heading/Heading.svelte")["default"]
    const Lead: typeof import("./src/lib/features/typography/components/lead/Lead.svelte")["default"]
    const MultiProvider: typeof import("./src/lib/features/providers/components/MultiProvider.svelte")["default"]
    const Muted: typeof import("./src/lib/features/typography/components/muted/Muted.svelte")["default"]
    const OrderedList: typeof import("./src/lib/features/typography/components/ordered-list/OrderedList.svelte")["default"]
    const Paragraph: typeof import("./src/lib/features/typography/components/paragraph/Paragraph.svelte")["default"]
    const Ripple: typeof import("./src/lib/features/ripple/components/ripple.svelte")["default"]
    const Small: typeof import("./src/lib/features/typography/components/small/Small.svelte")["default"]
    const UnorderedList: typeof import("./src/lib/features/typography/components/unordered-list/UnorderedList.svelte")["default"]
}

export {}
